name: Build and Publish Package

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  check_tag:
    runs-on: ubuntu-latest
    outputs:
      tag_exists: ${{ steps.tag_exists.outputs.exists }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get release version
        run: echo "PACKAGE_VERSION=$(cat .version)-$(cat .revision)" >> $GITHUB_ENV
      - name: Check if tag exists
        id: tag_exists
        run: git show-ref --tags --verify --quiet -- "refs/tags/v${{ env.PACKAGE_VERSION }}" && echo "::set-output name=exists::1" || echo "::set-output name=exists::0"
      - run: |
          git show-ref --tags --verify -- "refs/tags/v${{ env.PACKAGE_VERSION }}" || true
          echo "steps.tag_exists.outputs.exists = ${{ steps.tag_exists.outputs.exists }}"

  build:
    needs: check_tag
    if: needs.check_tag.outputs.tag_exists == 0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get release version
        run: |
          echo "PACKAGE_VERSION=$(cat .version)-$(cat .revision)" >> $GITHUB_ENV
      - name: Build package
        run: make deb
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{ env.PACKAGE_VERSION }}",
              sha: context.sha
            })
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: chroot-tools*.deb
          fail_on_unmatched_files: true
          tag_name: v${{ env.PACKAGE_VERSION }}
